### ISSUE TITLE
Sly won't start under Windows

### ISSUE THREAD

**Issue by asampal** [capitaomorte/sly#71]
I'm using Emacs 24.5 under Windows 10 64 bit

When I try to `M-x sly`, the `*inferior-lisp*` buffer stops with the following:

```
; C:/Users/adi/AppData/Local/common-lisp/sbcl-1.3.1-win-x64/d/dev/msys64/home/adi/.emacs.d/elpa/sly-20151215.654/slynk/backend/sbcl-TMP.fasl written
; compilation finished in 0:00:00.900

debugger invoked on a UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread
#<THREAD "main thread" RUNNING {1002AFBC53}>:
  COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "slynk" "backend" "sbcl">

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "slynk" "backend" "sbcl">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "slynk" "backend" "sbcl">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4: [ABORT                        ] Exit debugger, returning to top level.

(UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "slynk" "backend" "sbcl">)))
0]
```

I'm using sly-20151215.654 from Melpa.

**Comment by capitaomorte** [comment]
Might have been a recent change, and it looks to be SBCL-related, since I've been starting it under windows regularly, but using Allegro CL. Taking a look at it...

**Comment by capitaomorte** [comment]
I've reproduced the problem exactly. I don't exactly understand it still, but it seems to be ASDF-related. The compilation of the file itself works great, the error happens somewhere inside `UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS`, that is, it is the checking of compilation results itself that results in error. 

Perhaps @fare can shed some light here. The backtrace is 

```
(UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "slynk" "backend" "sbcl">)))
0] backtrace 10

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1002AFBC43}>
0: (UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "slynk" "backend" "sbcl">)))
1: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unavailable argument> #<unavailable argument> #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "slynk" "backend" "sbcl">)
2: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "slynk" "backend" "sbcl">) [fast-method]
3: ((:METHOD ASDF/PLAN:PERFORM-PLAN (LIST)) ((#1=#<ASDF/LISP-ACTION:PREPARE-OP > . #<ASDF/SYSTEM:SYSTEM #2="slynk">) (#1# . #3=#<ASDF/LISP-ACTION:CL-SOURCE-FILE #2# "slynk-backend">) (#4=#<ASDF/LISP-ACTION:LOAD-OP > . #3#) (#1# . #5=#<ASDF/LISP-ACTION:CL-SOURCE-FILE #2# "slynk-source-path-parser">) (#4# . #5#) (#1# . #6=#<ASDF/LISP-ACTION:CL-SOURCE-FILE #2# "slynk-source-file-cache">) (#4# . #6#) (#1# . #7=#<ASDF/COMPONENT:MODULE #2# #8="backend">) (#1# . #9=#<ASDF/LISP-ACTION:CL-SOURCE-FILE #2# #8# "sbcl">) (#10=#<ASDF/LISP-ACTION:COMPILE-OP > . #9#) (#4# . #9#) (#10# . #7#) ...) :FORCE NIL) [fast-method]
4: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
5: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) ((#1=#<ASDF/LISP-ACTION:PREPARE-OP > . #<ASDF/SYSTEM:SYSTEM #2="slynk">) (#1# . #3=#<ASDF/LISP-ACTION:CL-SOURCE-FILE #2# "slynk-backend">) (#4=#<ASDF/LISP-ACTION:LOAD-OP > . #3#) (#1# . #5=#<ASDF/LISP-ACTION:CL-SOURCE-FILE #2# "slynk-source-path-parser">) (#4# . #5#) (#1# . #6=#<ASDF/LISP-ACTION:CL-SOURCE-FILE #2# "slynk-source-file-cache">) (#4# . #6#) (#1# . #7=#<ASDF/COMPONENT:MODULE #2# #8="backend">) (#1# . #9=#<ASDF/LISP-ACTION:CL-SOURCE-FILE #2# #8# "sbcl">) (#10=#<ASDF/LISP-ACTION:COMPILE-OP > . #9#) (#4# . #9#) (#10# . #7#) ...)) [fast-method]
6: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
7: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1002EEDAC3}>) [fast-method]
8: ((:METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "slynk">) [fast-method]
9: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "slynk">)
```

Earlier versions (1.1.something) or SBCL work.,

As a workaround, use the traditional "slynk-loader" fallback that doesn't use ASDF by putting this in your .emacs

`(setq sly-init-function 'sly-init-using-slynk-loader)`

It should work.

**Comment by asampal** [comment]
That does it - thanks.

**Comment by capitaomorte** [comment]
Hopefully, I've fixed it properly and you can now remove the workaround.

**Comment by fare** [comment]
What was the warning on SBCL? The compilation policy is strict for a reason.

**Comment by capitaomorte** [comment]
A deprecation warning:

**Comment by capitaomorte** [comment]
Why is it stricter just on SBCL though?

**Comment by fare** [comment]
It has ALWAYS been that was on SBCL (since the very first ASDF, way before my time). Because SBCL and now MKCL, unlike other Lisps (that I know of), do have a very strict interpretation of WARNING vs STYLE-WARNING.

**Comment by capitaomorte** [comment]
Alright, man, I'm not arguing against setting it back, you said it is like that "for a reason", I was just curious to what the reason is.

Anyway, if SLY is to support many sbcl versions, including the bleeding edge, it has to thread a line between sprinkling the code with reader conditionals and using lenient defaults, which is what I did in  247c412. Don't you agree?

**Comment by capitaomorte** [comment]
> I'm not arguing against setting it back

Err, I meant "I'm not arguing _for_ setting it ~~back~~ [to `:warn`]".
Did you see my other suggestion about improving ASDF error reporting in these cases?

**Comment by fare** [comment]
The Right Thing™ is to actually support new and old SBCL versions by issuing no warning, using #. if needed. There are plenty of instances of that in UIOP, including for SBCL in image.lisp. (And if you could assume UIOP and ASDF in SLY...)

I think 247c412 is wrong-headed. You're going to accumulate bad warnings until it blows in your face again. Better an early failure than a time-bomb that's even harder to fix because you have to track down where it comes from.

**Comment by capitaomorte** [comment]
> using #. if needed

SLIME doesn't do it (It doesn't use ASDF as well) and there's an advantage to track SLIME here, at least for the time being. Also,  I don't have time to track SBCL details so closely.

> you have to track down where it comes from.

But this is what I had to do anyway in this case anyway.

In this particular case, when that deprecated function is removed (@luismbo tells me they make it an error before that), I'll have to dig just as deep.

> I think 247c412 is wrong-headed. 

It makes it the same as every other lisp, and I've not had many of these kinds of problems blow up in my face in allegro, for example.

> And if you could assume UIOP and ASDF in SLY...

What would be the advantage of that? Would that slim down `slynk\backend\*.lisp` files considerably? It's a bold move, but if the benefits are great I'm game. Would you help me convert them?

**Comment by fare** [comment]
It's not "same as every other lisp", because SBCL (and MKCL) has a different take on what a warning means.

Using ASDF would simplify the backends a bit. Downside is you require a recent implementation and/or must include ADSF in your package. Upside is you can rely on UIOP for portability, on ASDF for compilation... and for storing the .fasl at the same place as ASDF. I really hate that SLIME by default puts all the .fasl's at the same place, that conflict between implementations.

**Comment by capitaomorte** [comment]
> It's not "same as every other lisp", because SBCL (and MKCL) has a different take on what a warning means.

I don't understand what you mean. If I set `*compile-file-failure-behaviour*` to `:warn`, i'll face the kinds same problems in regarding different SBCL versions that I do regarding different Allegro versions. Regardless on the philosophical "take" that SBCL and MKCL have on the meaning of a warning. 

I actually happen to agree on that take, I just have no time to maintain SLY like that.

> I really hate that SLIME by default puts all the .fasl's at the same place, that conflict between implementations.

Actually, I don't think so, last I checked `swank-loader` discriminates by implementation. But surely you know this, you must be referring to something else.

> and for storing the .fasl at the same place as ASDF.

Ah you probably mean `C-c C-k` `sly-compile-file`. SLY behaves the same way as SLIME here. It stores the ASDF in the same directory as the file being compiled. I've never come across an actual problem caused by that. What exactly is the implementation-switch-related use case that you are experiencing problems with?

**Comment by fare** [comment]
Yes, I mean C-c C-k.

When I switch from one version of a compiler to the next, I need to manually clean the directory.
When I switch from SBCL to Allegro, both of which use ".fasl", I need to manually clean the directory.
When I share my home via NFS between two architectures, I'm f*ed.

**Comment by capitaomorte** [comment]
But why are you loading the `.fasl` file that you just created on a platform on a different platform?

Normally the `fasl` files that I create with `C-c C-k` are loaded only once in their lifetimes. At which point you may ask are they are created at all? Because occasionally I need manually transfer a specific file a a place where I know that particular fasl version is needed, such as when handing a patch to a client.

**Comment by fare** [comment]
Yeah, the fasl doesn't pollute my regular asdf build, or interfere too much with other instances of SLIME, unless used in parallel, which would suck badly.

Using a unique name, what more in ${TMPDIR:-/tmp}, would be much safer. UIOP has a with-temporary-file.

If you need to hand a patch to a client, there's no problem fetching it from the asdf cache. ASDF is far from perfect, but its build is probably more reproducible than what C-c C-k provides.

**Comment by capitaomorte** [comment]
> If you need to hand a patch to a client, there's no problem fetching it from the asdf cache. 

Yeah, I could, but where does it live? I never know. I actually don't want to know, which is a good thing, but I suspect it's a mile-long path. Anyway, a contrib that does this shouldn't be too hard to write.

**Comment by fare** [comment]
To be painfully correct: `(first (asdf:output-files :compile-op (pathname-component p)))` with `pathname-component` from swank-asdf (beware: may be nil if never compiled via asdf). Or just: `(uiop:compile-file-pathname* p)` which should always work, and be the same unless the user is doing something extra tricky.

**Comment by capitaomorte** [comment]
OK, I guess. So `slime-asdf` does what you want already? 

* If so, I can port it back to SLY, if you're interested. 

* If it doesn't do what you want and you wish you could augment it with more ASDF trickery, but can't because of the problems that arise from always loading the lisp-side of that contrib via "swank-loader", I think you already know that in SLY you don't have that problem: contribs can be loaded optionally and so you can cram bleeding-edge ASDFness into that hypothetical `sly-asdf` contrib.

**Comment by fare** [comment]
Well, it mostly does what I want, but
1- the maintainers have commented out that line:
`;;; (pushnew 'try-compile-file-with-asdf *compile-file-for-emacs-hook*)`
2- if `uiop` can be assumed to always be there, the default, fallback method would ideally also use `compile-file-pathname*` and/or `compile-file*` and through them, implicitly, `*output-translation-function*`

**Comment by capitaomorte** [comment]
1- I guess we can uncomment  that line in `sly-asdf`. I wouldn't mind having `.fasl`s go somewhere more sane, especially if we can give some feedback to the user about where that is.
2- I guess we can assume uiop "always there". A user that has an uiop/asdf-less lisp just won't add `sly-asdf` to his `sly-contribs`, though I suspect that will be rare.

I'll open an issue to keep track of this enhancement
